.TH FMIDI\-SEQ "1" "August 2021" "" "User Commands"
.SH NAME
fmidi\-seq \(en print the complete sequence from a MIDI file
.SH SYNOPSIS
.B fmidi\-seq
.I INPUT
.P
Reads the
.I INPUT
file and prints the MIDI sequence on
.BR stdout .
.SH "SEE\ ALSO"
.BR fmidi\-convert (1),
.BR fmidi\-grep (1),
.BR fmidi\-play (1),
.BR fmidi\-read (1)
