.TH FMIDI\-READ "1" "August 2021" "" "User Commands"
.SH NAME
fmidi\-read \(en validate MIDI files
.SH SYNOPSIS
.B fmidi\-read
.I INPUT
.RI [ INPUT \ ...]
.P
Reads each
.I INPUT
file and prints any errors.
.SH "EXIT\ STATUS"
.TP
.B 0
if all
.I INPUT
files were free of errors
.TP
.B 1
if any error was reported in an
.I INPUT
file
.SH "SEE\ ALSO"
.BR fmidi\-convert (1),
.BR fmidi\-grep (1),
.BR fmidi\-play (1),
.BR fmidi\-seq (1)
