.TH FMIDI\-CONVERT "1" "August 2021" "" "User Commands"
.SH NAME
fmidi\-convert \(en convert to Standard Midi Files (SMF)
.SH SYNOPSIS
.B fmidi\-convert
.I INPUT
.P
Converts an
.I INPUT
file in any supported format to Standard Midi Files (SMF) format and writes the result on
.BR stdout .
The output should be redirected to a file or piped to another command.
.SH "SEE\ ALSO"
.BR fmidi\-grep (1),
.BR fmidi\-play (1),
.BR fmidi\-read (1),
.BR fmidi\-seq (1)
